# Generated by Django 5.0.7 on 2026-06-06 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        ('vendors', '0002_vendor_vendors_ven_status_2dcb2a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['status'], name='procurement_status_5f9a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['approver', 'status'], name='procurement_approve_50686f_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['quotation'], name='procurement_quotati_2fd423_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['created_at'], name='procurement_created_18cc5d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['module', 'action'], name='procurement_module_f2db9b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='procurement_created_d72953_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='procurement_user_id_45ccfb_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='procurement_status_f9a17b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='procurement_invoice_79a2a9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='procurement_due_dat_ea28d9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['created_at'], name='procurement_created_e9e121_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='procurement_user_id_22b73e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='procurement_notific_b7b40b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='procurement_created_d1f4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='procurement_status_6b6895_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['created_at'], name='procurement_created_164010_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['status'], name='procurement_status_0e379b_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['rfq', 'status'], name='procurement_rfq_id_4f3fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['vendor', 'status'], name='procurement_vendor__5d78f8_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['price'], name='procurement_price_777739_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['delivery_days'], name='procurement_deliver_b59459_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['created_at'], name='procurement_created_35f728_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['status'], name='procurement_status_a60a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['deadline'], name='procurement_deadlin_baeb31_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['created_by', 'status'], name='procurement_created_10d3aa_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['created_at'], name='procurement_created_f01f0b_idx'),
        ),
        migrations.AddIndex(
            model_name='rfqitem',
            index=models.Index(fields=['rfq'], name='procurement_rfq_id_943600_idx'),
        ),
        migrations.AddIndex(
            model_name='rfqitem',
            index=models.Index(fields=['product_name'], name='procurement_product_b0eb7a_idx'),
        ),
    ]
