# Generated by Django 5.0.7 on 2026-06-06 05:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_approval_procurement_status_5f9a4e_idx_and_more'),
        ('vendors', '0003_vendor_is_deleted_vendor_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rfq',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rfq',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['is_deleted', 'status'], name='procurement_is_dele_32ddc8_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(fields=('rfq', 'vendor'), name='unique_quotation_per_rfq_vendor'),
        ),
    ]
