# Generated by Django 5.0.7 on 2026-06-06 07:00

import apps.procurement.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_alter_quotation_unique_together_rfq_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='quotation_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'csv', 'png', 'jpg', 'jpeg']), apps.procurement.models.validate_upload_size]),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='rfq_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'csv', 'png', 'jpg', 'jpeg']), apps.procurement.models.validate_upload_size]),
        ),
    ]
