# Generated by Django 5.0.7 on 2026-06-06 09:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_alter_quotation_attachment_alter_rfq_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfqitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
