# Generated by Django 5.0.7 on 2026-06-06 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['status'], name='vendors_ven_status_2dcb2a_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['category'], name='vendors_ven_categor_93852f_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['company_name'], name='vendors_ven_company_3db4b3_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['email'], name='vendors_ven_email_3112dd_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['gst_number'], name='vendors_ven_gst_num_33e6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['created_at'], name='vendors_ven_created_c4e3ec_idx'),
        ),
    ]
