# Generated by Django 5.0.7 on 2026-06-06 05:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_vendors_ven_status_2dcb2a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['is_deleted', 'status'], name='vendors_ven_is_dele_db4a91_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(condition=models.Q(('gst_number', ''), _negated=True), fields=('gst_number',), name='unique_nonblank_vendor_gst_number'),
        ),
    ]
